import {
  Cruise,
  Booking,
  DeckVenue,
  ScheduleEvent,
  TransferOption,
  ParkingOption,
} from "./types";

export const cruises: Cruise[] = [
  {
    id: "med-dream-7",
    name: "Mediterranean Dream",
    shipName: "MS Ocean Dream",
    description:
      "Sail the azure waters of the Mediterranean visiting iconic ports from Barcelona to Naples. Enjoy world-class dining, entertainment, and relaxation aboard the stunning MS Ocean Dream.",
    image: "/images/cruise-med.jpg",
    duration: 7,
    region: "Mediterranean",
    departureDate: "2026-07-15",
    returnDate: "2026-07-22",
    rating: 4.7,
    reviewCount: 2847,
    highlights: [
      "Gaudi's Barcelona",
      "French Riviera",
      "Roman Colosseum",
      "Amalfi Coast",
    ],
    ports: [
      {
        id: "bcn",
        name: "Barcelona",
        country: "Spain",
        lat: 41.3851,
        lng: 2.1734,
        departureTime: "17:00",
        day: 1,
        timezone: "Europe/Madrid",
        utcOffset: 2,
      },
      {
        id: "mrs",
        name: "Marseille",
        country: "France",
        lat: 43.2965,
        lng: 5.3698,
        arrivalTime: "08:00",
        departureTime: "18:00",
        day: 3,
        timezone: "Europe/Paris",
        utcOffset: 2,
      },
      {
        id: "rom",
        name: "Civitavecchia (Rome)",
        country: "Italy",
        lat: 42.0933,
        lng: 11.7967,
        arrivalTime: "07:00",
        departureTime: "19:00",
        day: 4,
        timezone: "Europe/Rome",
        utcOffset: 2,
      },
      {
        id: "nap",
        name: "Naples",
        country: "Italy",
        lat: 40.8518,
        lng: 14.2681,
        arrivalTime: "08:00",
        departureTime: "17:00",
        day: 5,
        timezone: "Europe/Rome",
        utcOffset: 2,
      },
      {
        id: "bcn-ret",
        name: "Barcelona",
        country: "Spain",
        lat: 41.3851,
        lng: 2.1734,
        arrivalTime: "09:00",
        day: 7,
        timezone: "Europe/Madrid",
        utcOffset: 2,
      },
    ],
    cabins: [
      {
        id: "interior",
        name: "Interior Cabin",
        description: "Cozy interior cabin with all essential amenities",
        pricePerNight: 89,
        maxGuests: 2,
        amenities: ["Twin/King bed", "Private bathroom", "TV", "Mini fridge", "Safe"],
        image: "/images/cabin-interior.jpg",
        available: 45,
      },
      {
        id: "ocean-view",
        name: "Ocean View Cabin",
        description: "Bright cabin with a porthole window overlooking the sea",
        pricePerNight: 129,
        maxGuests: 2,
        amenities: [
          "Ocean view window",
          "Twin/King bed",
          "Private bathroom",
          "TV",
          "Mini fridge",
          "Safe",
        ],
        image: "/images/cabin-oceanview.jpg",
        available: 32,
      },
      {
        id: "balcony",
        name: "Balcony Cabin",
        description:
          "Spacious cabin with a private balcony for stunning sea views",
        pricePerNight: 189,
        maxGuests: 3,
        amenities: [
          "Private balcony",
          "King bed",
          "Sofa bed",
          "Private bathroom",
          "TV",
          "Mini bar",
          "Safe",
          "Bathrobe",
        ],
        image: "/images/cabin-balcony.jpg",
        available: 20,
      },
      {
        id: "suite",
        name: "Grand Suite",
        description:
          "Luxurious suite with separate living area, premium amenities, and butler service",
        pricePerNight: 349,
        maxGuests: 4,
        amenities: [
          "Large balcony",
          "King bed",
          "Separate living room",
          "Jacuzzi tub",
          "Walk-in closet",
          "Premium mini bar",
          "Butler service",
          "Priority boarding",
        ],
        image: "/images/cabin-suite.jpg",
        available: 8,
      },
    ],
  },
  {
    id: "greek-isles-5",
    name: "Greek Islands Explorer",
    shipName: "MS Aegean Star",
    description:
      "Discover the magic of the Greek Islands with stops at Mykonos, Santorini, and Crete.",
    image: "/images/cruise-greek.jpg",
    duration: 5,
    region: "Mediterranean",
    departureDate: "2026-08-01",
    returnDate: "2026-08-06",
    rating: 4.8,
    reviewCount: 1923,
    highlights: [
      "Santorini sunsets",
      "Mykonos nightlife",
      "Cretan cuisine",
      "Ancient ruins",
    ],
    ports: [
      {
        id: "ath",
        name: "Piraeus (Athens)",
        country: "Greece",
        lat: 37.9475,
        lng: 23.6372,
        departureTime: "18:00",
        day: 1,
        timezone: "Europe/Athens",
        utcOffset: 3,
      },
      {
        id: "myk",
        name: "Mykonos",
        country: "Greece",
        lat: 37.4467,
        lng: 25.3289,
        arrivalTime: "08:00",
        departureTime: "20:00",
        day: 2,
        timezone: "Europe/Athens",
        utcOffset: 3,
      },
      {
        id: "san",
        name: "Santorini",
        country: "Greece",
        lat: 36.3932,
        lng: 25.4615,
        arrivalTime: "07:00",
        departureTime: "18:00",
        day: 3,
        timezone: "Europe/Athens",
        utcOffset: 3,
      },
      {
        id: "cre",
        name: "Heraklion (Crete)",
        country: "Greece",
        lat: 35.3387,
        lng: 25.1442,
        arrivalTime: "09:00",
        departureTime: "17:00",
        day: 4,
        timezone: "Europe/Athens",
        utcOffset: 3,
      },
      {
        id: "ath-ret",
        name: "Piraeus (Athens)",
        country: "Greece",
        lat: 37.9475,
        lng: 23.6372,
        arrivalTime: "08:00",
        day: 5,
        timezone: "Europe/Athens",
        utcOffset: 3,
      },
    ],
    cabins: [
      {
        id: "interior",
        name: "Interior Cabin",
        description: "Comfortable interior cabin",
        pricePerNight: 99,
        maxGuests: 2,
        amenities: ["Twin/King bed", "Private bathroom", "TV", "Mini fridge"],
        image: "/images/cabin-interior.jpg",
        available: 30,
      },
      {
        id: "balcony",
        name: "Balcony Cabin",
        description: "Cabin with private balcony",
        pricePerNight: 199,
        maxGuests: 3,
        amenities: ["Private balcony", "King bed", "Private bathroom", "TV", "Mini bar"],
        image: "/images/cabin-balcony.jpg",
        available: 15,
      },
    ],
  },
  {
    id: "norway-fjords-10",
    name: "Norwegian Fjords Adventure",
    shipName: "MS Northern Light",
    description:
      "Explore the breathtaking fjords of Norway with stops at Bergen, Geiranger, and Tromsoe.",
    image: "/images/cruise-norway.jpg",
    duration: 10,
    region: "Northern Europe",
    departureDate: "2026-06-20",
    returnDate: "2026-06-30",
    rating: 4.9,
    reviewCount: 1456,
    highlights: [
      "Geirangerfjord",
      "Northern Lights",
      "Viking history",
      "Midnight sun",
    ],
    ports: [
      {
        id: "sou",
        name: "Southampton",
        country: "UK",
        lat: 50.9097,
        lng: -1.4044,
        departureTime: "16:00",
        day: 1,
        timezone: "Europe/London",
        utcOffset: 1,
      },
      {
        id: "ber",
        name: "Bergen",
        country: "Norway",
        lat: 60.3913,
        lng: 5.3221,
        arrivalTime: "10:00",
        departureTime: "20:00",
        day: 3,
        timezone: "Europe/Oslo",
        utcOffset: 2,
      },
      {
        id: "gei",
        name: "Geiranger",
        country: "Norway",
        lat: 62.1008,
        lng: 7.206,
        arrivalTime: "08:00",
        departureTime: "18:00",
        day: 5,
        timezone: "Europe/Oslo",
        utcOffset: 2,
      },
      {
        id: "tro",
        name: "Tromsoe",
        country: "Norway",
        lat: 69.6496,
        lng: 18.956,
        arrivalTime: "07:00",
        departureTime: "17:00",
        day: 7,
        timezone: "Europe/Oslo",
        utcOffset: 2,
      },
      {
        id: "sou-ret",
        name: "Southampton",
        country: "UK",
        lat: 50.9097,
        lng: -1.4044,
        arrivalTime: "08:00",
        day: 10,
        timezone: "Europe/London",
        utcOffset: 1,
      },
    ],
    cabins: [
      {
        id: "interior",
        name: "Interior Cabin",
        description: "Cozy interior cabin",
        pricePerNight: 109,
        maxGuests: 2,
        amenities: ["Twin/King bed", "Private bathroom", "TV", "Mini fridge"],
        image: "/images/cabin-interior.jpg",
        available: 50,
      },
      {
        id: "ocean-view",
        name: "Ocean View Cabin",
        description: "Cabin with ocean view",
        pricePerNight: 159,
        maxGuests: 2,
        amenities: ["Ocean view", "King bed", "Private bathroom", "TV", "Mini fridge"],
        image: "/images/cabin-oceanview.jpg",
        available: 25,
      },
      {
        id: "balcony",
        name: "Balcony Cabin",
        description: "Cabin with private balcony",
        pricePerNight: 229,
        maxGuests: 3,
        amenities: ["Private balcony", "King bed", "Private bathroom", "TV", "Mini bar"],
        image: "/images/cabin-balcony.jpg",
        available: 18,
      },
    ],
  },
];

// Demo user's active booking (for the Mediterranean cruise)
export const activeBooking: Booking = {
  id: "BK-2026-0715",
  cruiseId: "med-dream-7",
  cabinCategoryId: "balcony",
  cabinNumber: "B-742",
  guestName: "Alex Johnson",
  guestEmail: "alex@example.com",
  guests: 2,
  totalPrice: 2646,
  status: "confirmed",
  bookingDate: "2026-03-10",
};

// Ship deck venues for MS Ocean Dream
export const deckVenues: DeckVenue[] = [
  // Deck 4 - Main/Entertainment
  { id: "theater", name: "Grand Theater", type: "theater", deck: 4, x: 10, y: 20, width: 25, height: 60, description: "800-seat theater with Broadway-style shows", openHours: "19:00-23:00" },
  { id: "lobby", name: "Grand Lobby", type: "lounge", deck: 4, x: 40, y: 25, width: 15, height: 50, description: "Stunning atrium with guest services and art gallery" },
  { id: "restaurant-main", name: "The Grand Dining Room", type: "restaurant", deck: 4, x: 60, y: 15, width: 30, height: 35, description: "Main dining room with 5-course dinner service", openHours: "06:30-10:00, 12:00-14:00, 18:00-22:00" },
  { id: "bar-atrium", name: "Atrium Bar", type: "bar", deck: 4, x: 60, y: 55, width: 15, height: 25, description: "Cocktail bar in the heart of the ship", openHours: "11:00-01:00" },
  { id: "shop-main", name: "Boutique Gallery", type: "shop", deck: 4, x: 78, y: 55, width: 12, height: 25, description: "Duty-free shopping and souvenirs", openHours: "09:00-22:00" },

  // Deck 7 - Cabins
  { id: "cabins-7-port", name: "Balcony Cabins (Port)", type: "cabin", deck: 7, x: 5, y: 5, width: 90, height: 20, description: "Balcony cabins B-700 to B-750" },
  { id: "cabins-7-star", name: "Balcony Cabins (Starboard)", type: "cabin", deck: 7, x: 5, y: 75, width: 90, height: 20, description: "Balcony cabins B-751 to B-799" },
  { id: "restaurant-buffet", name: "Ocean Buffet", type: "restaurant", deck: 7, x: 65, y: 30, width: 30, height: 40, description: "International buffet with ocean views", openHours: "06:00-22:00" },
  { id: "bar-pool", name: "Sunset Bar", type: "bar", deck: 7, x: 5, y: 30, width: 15, height: 40, description: "Poolside cocktails and smoothies", openHours: "10:00-00:00" },

  // Deck 9 - Pool & Recreation
  { id: "pool-main", name: "Main Pool", type: "pool", deck: 9, x: 25, y: 25, width: 25, height: 50, description: "Large outdoor pool with retractable roof" },
  { id: "pool-kids", name: "Kids Splash Zone", type: "kids", deck: 9, x: 55, y: 25, width: 15, height: 30, description: "Water playground for children", openHours: "08:00-20:00" },
  { id: "spa", name: "Serenity Spa", type: "spa", deck: 9, x: 5, y: 15, width: 18, height: 70, description: "Full-service spa with sauna and steam room", openHours: "08:00-20:00" },
  { id: "gym", name: "Fitness Center", type: "gym", deck: 9, x: 75, y: 15, width: 20, height: 35, description: "State-of-the-art gym with ocean views", openHours: "06:00-22:00" },
  { id: "bar-sky", name: "Sky Lounge", type: "lounge", deck: 9, x: 75, y: 55, width: 20, height: 30, description: "Premium lounge with panoramic views", openHours: "16:00-02:00" },
  { id: "kids-club", name: "Adventure Kids Club", type: "kids", deck: 9, x: 55, y: 60, width: 15, height: 25, description: "Supervised activities for ages 3-12", openHours: "09:00-21:00" },
];

// Schedule events for the cruise
export const scheduleEvents: ScheduleEvent[] = [
  // Day 1 - Departure from Barcelona
  { id: "e1", title: "Welcome Aboard Cocktail Party", description: "Meet your fellow passengers and crew with champagne and canapes", category: "social", venue: "Grand Lobby", deck: 4, startTime: "17:30", endTime: "18:30", day: 1 },
  { id: "e2", title: "Safety Drill", description: "Mandatory safety drill for all passengers", category: "social", venue: "Muster Stations", deck: 4, startTime: "18:30", endTime: "19:00", day: 1 },
  { id: "e3", title: "Gala Dinner", description: "Five-course welcome dinner with the Captain", category: "food", venue: "The Grand Dining Room", deck: 4, startTime: "19:30", endTime: "21:30", day: 1 },
  { id: "e4", title: "Welcome Show: Mediterranean Nights", description: "Song and dance spectacular celebrating Mediterranean culture", category: "show", venue: "Grand Theater", deck: 4, startTime: "21:30", endTime: "23:00", day: 1 },
  { id: "e5", title: "DJ Party on Deck", description: "Dance under the stars with DJ Marco", category: "music", venue: "Main Pool", deck: 9, startTime: "23:00", endTime: "01:00", day: 1 },

  // Day 2 - Sea Day
  { id: "e6", title: "Sunrise Yoga", description: "Start your day with yoga overlooking the ocean", category: "wellness", venue: "Main Pool", deck: 9, startTime: "07:00", endTime: "08:00", day: 2 },
  { id: "e7", title: "Morning Trivia", description: "Test your knowledge and win prizes", category: "social", venue: "Sky Lounge", deck: 9, startTime: "10:00", endTime: "11:00", day: 2 },
  { id: "e8", title: "Cooking Class: Paella Workshop", description: "Learn to make authentic Spanish paella with Chef Garcia", category: "food", venue: "Ocean Buffet", deck: 7, startTime: "11:00", endTime: "12:30", day: 2 },
  { id: "e9", title: "Pool Games & Competitions", description: "Water polo, relay races, and belly flop contest", category: "sport", venue: "Main Pool", deck: 9, startTime: "14:00", endTime: "16:00", day: 2 },
  { id: "e10", title: "Kids Pirate Adventure", description: "Treasure hunt and pirate games for little ones", category: "kids", venue: "Adventure Kids Club", deck: 9, startTime: "14:00", endTime: "16:00", day: 2 },
  { id: "e11", title: "Wine Tasting: Mediterranean Reds", description: "Sample premium wines from Spain, France, and Italy", category: "food", venue: "Atrium Bar", deck: 4, startTime: "16:30", endTime: "17:30", day: 2 },
  { id: "e12", title: "Formal Night Dinner", description: "Elegant dining experience with a special menu", category: "food", venue: "The Grand Dining Room", deck: 4, startTime: "19:00", endTime: "21:00", day: 2 },
  { id: "e13", title: "Comedy Night", description: "Stand-up comedy with international performers", category: "show", venue: "Grand Theater", deck: 4, startTime: "21:00", endTime: "22:30", day: 2 },
  { id: "e14", title: "Latin Dance Night", description: "Salsa, bachata, and merengue with live band", category: "music", venue: "Sky Lounge", deck: 9, startTime: "22:30", endTime: "01:00", day: 2 },

  // Day 3 - Marseille
  { id: "e15", title: "Port Talk: Marseille", description: "Everything you need to know about today's port", category: "social", venue: "Grand Theater", deck: 4, startTime: "07:30", endTime: "08:00", day: 3 },
  { id: "e16", title: "Marseille Walking Tour (excursion)", description: "Guided tour of Old Port and Notre-Dame de la Garde", category: "social", venue: "Gangway", deck: 4, startTime: "09:00", endTime: "13:00", day: 3 },
  { id: "e17", title: "French Pastry Masterclass", description: "Learn croissants and macarons from our French pastry chef", category: "food", venue: "Ocean Buffet", deck: 7, startTime: "14:00", endTime: "15:30", day: 3 },
  { id: "e18", title: "Spa Special: Lavender Treatment", description: "Provence-inspired relaxation package", category: "wellness", venue: "Serenity Spa", deck: 9, startTime: "10:00", endTime: "18:00", day: 3 },
  { id: "e19", title: "Kids Movie Night", description: "Animated feature film with popcorn and snacks", category: "kids", venue: "Adventure Kids Club", deck: 9, startTime: "19:00", endTime: "21:00", day: 3 },
  { id: "e20", title: "French Cabaret Show", description: "An evening of French music, dance, and elegance", category: "show", venue: "Grand Theater", deck: 4, startTime: "21:00", endTime: "22:30", day: 3 },
];

export const transferOptions: TransferOption[] = [
  {
    id: "own-car",
    type: "car",
    name: "Drive Your Own Car",
    description: "Park at or near the cruise terminal and walk to the ship",
    priceRange: "\u20ac10-25/day",
    details: [
      "Several parking garages within walking distance",
      "Long-term parking rates available for cruise passengers",
      "Book in advance for best rates",
    ],
    tips: [
      "Arrive at least 30 minutes early to park and walk",
      "Take a photo of your parking spot",
      "Remove all valuables from the car",
      "Check your battery and tyre pressure before leaving",
    ],
  },
  {
    id: "taxi",
    type: "taxi",
    name: "Taxi / Ride Share",
    description: "Door-to-door service from your home or hotel",
    priceRange: "\u20ac15-60",
    details: [
      "Drop-off directly at the terminal entrance",
      "Uber and Bolt available in Barcelona",
      "Pre-book for fixed rates from airport",
    ],
    tips: [
      "Book a larger vehicle if you have heavy luggage",
      "Confirm the fare before starting the ride",
      "Allow extra time during peak hours",
    ],
  },
  {
    id: "shuttle",
    type: "shuttle",
    name: "Port Shuttle",
    description: "Shared shuttle service from major hotels and airport",
    priceRange: "\u20ac8-15 per person",
    details: [
      "Runs every 30 minutes from key pickup points",
      "Airport shuttle available from Barcelona El Prat",
      "Luggage included in price",
    ],
    tips: [
      "Book at least 24 hours in advance",
      "Be at the pickup point 10 minutes early",
      "Confirm return shuttle for disembarkation day",
    ],
  },
  {
    id: "public-transport",
    type: "public",
    name: "Public Transport",
    description: "Metro, bus, or train to the port area",
    priceRange: "\u20ac2-5",
    details: [
      "Metro L3 to Drassanes + 15 min walk or port bus",
      "Bus T3 (Port Bus) from Placa de Colom",
      "Train to Passeig de Gracia, then metro",
    ],
    tips: [
      "Not recommended with heavy luggage",
      "Buy a T-Casual card for multiple rides",
      "Check schedules on TMB app",
      "Allow at least 1 hour from city center",
    ],
  },
];

export const parkingOptions: ParkingOption[] = [
  {
    id: "p1",
    name: "Port Vell Parking",
    address: "Moll de Barcelona, Port Terminal",
    pricePerDay: 22,
    distanceToTerminal: "200m (3 min walk)",
    shuttle: false,
    covered: true,
  },
  {
    id: "p2",
    name: "SABA Moll de la Fusta",
    address: "Passeig de Colom, 2",
    pricePerDay: 18,
    distanceToTerminal: "800m (10 min walk)",
    shuttle: false,
    covered: true,
  },
  {
    id: "p3",
    name: "CruisePark Barcelona",
    address: "Carrer de l'Escar, 15",
    pricePerDay: 12,
    distanceToTerminal: "1.5km",
    shuttle: true,
    covered: false,
  },
];

export const departureChecklist = [
  { id: "c1", text: "Passport / ID (valid for 6+ months)", category: "documents" },
  { id: "c2", text: "Booking confirmation printout", category: "documents" },
  { id: "c3", text: "Travel insurance documents", category: "documents" },
  { id: "c4", text: "Credit/debit cards", category: "documents" },
  { id: "c5", text: "Medications & prescriptions", category: "health" },
  { id: "c6", text: "Sunscreen SPF 50+", category: "health" },
  { id: "c7", text: "Motion sickness remedies", category: "health" },
  { id: "c8", text: "Phone charger & power bank", category: "electronics" },
  { id: "c9", text: "Camera", category: "electronics" },
  { id: "c10", text: "Universal power adapter", category: "electronics" },
  { id: "c11", text: "Formal outfit for gala nights", category: "clothing" },
  { id: "c12", text: "Swimwear", category: "clothing" },
  { id: "c13", text: "Comfortable walking shoes", category: "clothing" },
  { id: "c14", text: "Light jacket / layers", category: "clothing" },
  { id: "c15", text: "Day backpack for port excursions", category: "accessories" },
];

export const demoUser = {
  name: "Alex Johnson",
  email: "alex@example.com",
  avatar: "AJ",
};
